version: '3'
services:
  server:
    build:
      context: ./production/server
    restart: unless-stopped
    hostname: server
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - "./production/server/:/var/www/server/"

  db:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      TZ: "Europe/Warsaw"
    volumes:
      - "./deploy/init/:/docker-entrypoint-initdb.d/"
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 27017:27017

  octopi_dev-1:
    image: octoprint/octoprint
    hostname: octopi-dev-1
    networks:
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./data/octoprint-dev-1:/octoprint

  octopi_dev-2:
    image: octoprint/octoprint
    hostname: octopi-dev-2
    networks:
      - backend
    ports:
      - "8082:80"
    volumes:
      - ./data/octoprint-dev-2:/octoprint

networks:
  backend:
  frontend:
